/*
 * PPT Tools: Replay Injector
 *
 * Description:
 *     If given a replay demo generated by "replay_dump" (has the "DEM"
 *     extension), this tool will let you "inject" it into an existing Puyo
 *     Puyo Tetris "data.bin" save file for replaying in the built-in
 *     theatre mode. Be very careful. It is entirely possible to overwrite
 *     existing demos with this tool. It WILL warn you before replacing one
 *     (whenever I actually implement that).
 *
 *     If a position isn't given, the tool will try to "push" the replay to
 *     be the most recent valid replay available. The game allows replays to be
 *     out of order. If there are more than 50 replays, though, it will fail.
 *
 * Author:
 *     Clara Nguyen (@iDestyKK)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "util/ppt_addr.h"

typedef unsigned char  byte;
typedef unsigned short ushort;

int main(int argc, char** argv) {
	//Argument Check
	if (argc < 3 || argc > 4) {
		fprintf(stderr, "Usage: %s data.bin replay.dem [position]\n", argv[0]);
		return 1;
	}

	FILE        *fp;
	size_t       fsz;
	byte        *bin;
	unsigned int pos, i, replay_num, inject_pos;
	byte         replay_PREP[PREP_LEN],
	             replay_DATA[DATA_LEN];

	//First, we need to figure out the number of valid replays.
	fp = fopen(argv[1], "rb");

	//Get file size
	fseek(fp, 0, SEEK_END);
	fsz = ftell(fp);
	rewind(fp);

	//Allocate memory and read in all bytes
	bin = (byte *) malloc(sizeof(byte) * fsz);
	fread(bin, sizeof(byte), fsz, fp);

	//We are done here.
	fclose(fp);

	//Until 50, check for "PREP". This is how many replays there are.
	pos = PREP_LOC;
	for (replay_num = 0; replay_num < 50; replay_num++) {
		if (*(int*)& bin[pos] != 0x50455250)
			break;
		pos += PREP_LEN;
	}

	//Check argv[4].
	if (argc == 4) {
		inject_pos = atoi(argv[3]);

		//Do not allow gaps.
		if (inject_pos < 0 || inject_pos > replay_num - (replay_num == 50)) {
			fprintf(
				stderr,
				"Error: Value must be between 0-%d (inclusive)\n",
				replay_num - (replay_num == 50)
			);

			return 2;
		}
	}
	else {
		inject_pos = replay_num;

		//Whine if this causes 51 replays to be in the save.
		if (inject_pos >= 50) {
			fprintf(
				stderr,
				"Error: Doing this would result in 51 replays total!.\n"
			);

			return 3;
		}
	}

	//Make backup file
	fp = fopen("data.bin.bak", "wb");
	fwrite(bin, sizeof(byte), fsz, fp);
	fclose(fp);

	//Make the stupid assumption that everything is valid, inject, and dump.
	//Open the replay file and read bytes.
	fp = fopen(argv[2], "rb");

	fread(&replay_PREP[0], sizeof(byte), PREP_LEN, fp);
	fread(&replay_DATA[0], sizeof(byte), DATA_LEN, fp);

	fclose(fp);

	//Modify the save in memory
	memcpy(
		&bin[PREP_LOC + (PREP_LEN * inject_pos)],
		&replay_PREP[0],
		PREP_LEN
	);

	memcpy(
		&bin[DATA_LOC + (DATA_LEN * inject_pos)],
		&replay_DATA[0],
		DATA_LEN
	);

	//Finally, dump the save
	fp = fopen(argv[1], "wb");
	fwrite(bin, sizeof(byte), fsz, fp);
	fclose(fp);

	//Clean up
	free(bin);
	return 0;
}
